### ISSUE TITLE
使用了react-router后，NavItem应该提供Link的功能

### ISSUE THREAD

**Issue by J-F-Liu** [amazeui/amazeui-react#107]
使用了react-router后，NavItem应该提供Link的功能，而不只是一个纯粹的链接
比如：
```
<NavItem to="/">首页</NavItem>
```
或者支持：
```
<NavItem><Link to="/">首页</Link></NavItem>
```

**Comment by minwe** [comment]
> `linkComponent`: `node` - 渲染链接的组件，用于传递 React Router Link 组件等需求；
`linkProps`: `object` - 应用到 linkComponent 上的属性。

文档中有相关接口说明，例子里面也有相关使用：https://github.com/amazeui/amazeui-react/blob/master/examples/admin/components/Header.js#L56-L65。

**Comment by J-F-Liu** [comment]
看到了，谢谢
