### ISSUE TITLE
GoTop组件报错

### ISSUE THREAD

**Issue by mullezki** [amazeui/amazeui-react#109]
最近从1.0.1升级到1.1.0了，发现只要GoTop组件加了autoHide属性就会报错
![error1](http://web-gn1x.oss-cn-beijing.aliyuncs.com/bug/1.png)
![error2](http://web-gn1x.oss-cn-beijing.aliyuncs.com/bug/2.png)

**Comment by minwe** [comment]
可能是你打包了不同版本的 React，尝试把 node_modules 删除了重新安装，你项目依赖的 React 版本改为 `^0.14.8`。

**Comment by mullezki** [comment]
果然是react版本错了- -||
