### ISSUE TITLE
ie10下日期选择组件弹不出来, 原因是js报错,  navigator.language在ie10下是null 

### ISSUE THREAD

**Issue by allanfish** [amazeui/amazeui-react#110]
具体报错的[代码](https://github.com/amazeui/amazeui-react/blob/master/src/utils/dateUtils.js#L38)

**Comment by minwe** [comment]
参考 https://gist.github.com/ksol/62b489572944ca70b4ba

**Comment by minwe** [comment]
https://github.com/amazeui/amazeui-react/blob/63e556f87a91b749f41628d493fca79a3b8690d5/src/utils/dateUtils.js#L39

报错的其实是这一行：

```javascript
locale[1] = locale[1].toUpperCase();
```

**Comment by allanfish** [comment]
OK. 我已经在最新的代码中看到
