### ISSUE TITLE
Uncaught Error: Invariant Violation: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by zhang-z** [amazeui/amazeui-react#111]
我在使用Tabs时触发了以下报错：

> invariant.js:39 Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

疑似原因是项目载入了两个react instance。重现步骤：

    clone git@github.com:amazeui/react-starter-kit.git
    cd react-starter-kit && npm install
    npm uninstall react react-dom
    npm install react@0.14.0 react-dom@0.14.0
    npm start 

然后可在browser的console里面可以见到该错误提示

参考[该贴](http://stackoverflow.com/questions/28519287/what-does-only-a-reactowner-can-have-refs-mean)，解决方案是在amazeui-react的package.json中，把react, react-dom移入peerDependencies：

> Make sure NOT to list react under dependencies in your package.json.
> This is why we have peerDependencies ;-)

**Comment by minwe** [comment]
NPM 3 已经不支持 `peerDependencies` 了。

Webpack 可以配置只打包特定版本的模块，Browserify 貌似没有 这个选项。

```js
resolve: {
  alias: {
    react: __dirname + '/node_modules/react',
    'react-dom': __dirname + '/node_modules/react-dom'
  }
}
```

**Comment by zhang-z** [comment]
NPM 3 是修改`peerDependencies`的行为哦 ([NPM blog](http://blog.npmjs.org/post/110924823920/npm-weekly-5), [NPM ChangeLog](https://github.com/npm/npm/releases/tag/v3.0.0))：

> We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies.

我也是用webpack，没研究过Browserify的情况

**Comment by minwe** [comment]
嗯，一般项目依赖中都会加 React 相关依赖，所以 `peerDependencies ` 不自动安装一般也不会有问题。
