### ISSUE TITLE
图片轮播貌似有bug

### ISSUE THREAD

**Issue by Daniel9102** [amazeui/amazeui-react#116]
## 问题描述

（图片轮播在切换第二页以后会出现两个轮播图）

![image](https://cloud.githubusercontent.com/assets/13145894/14971984/508955b4-110a-11e6-8c98-ffeb43839936.png)
求帮助

**Comment by minwe** [comment]
Issue 模板中已经说明应该提供哪些信息，以便验证问题。

没有具体的信息无法验证。

**Comment by minwe** [comment]
问题产生环境不清，且长时间未反馈，无法验证，作关闭处理。
