### ISSUE TITLE
bower 安装出现问题

### ISSUE THREAD

**Issue by classtag** [amazeui/amazeui-react#117]
根据手册：
bower install amazeui-react
出现下面错误：
bower react-dom#^0.14.3        ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/EtienneLem/react-dom.git", exit code of #128 remote: Repository not found. fatal: repository 'https://github.com/EtienneLem/react-dom.git/' not found

**Comment by classtag** [comment]
最新的react中已经包含了react-dom.js

**Comment by minwe** [comment]
建议使用 NPM，Bower 已经不太适应时下流行的开发方式了。

**Comment by minwe** [comment]
有待发布新版本后进行测试。

**Comment by minwe** [comment]
https://github.com/amazeui/amazeui-react/releases/tag/v1.1.2 中已经修复。
