### ISSUE TITLE
请问用amazeui-react如何集成第三方插件

### ISSUE THREAD

**Issue by tihumihu** [amazeui/amazeui-react#120]
目前用到视频播放的组件，不知道如何集成到amazeui-react里。是要自己封装成组件吗？可以拿第三方的插件作为文件引用吗？

**Comment by minwe** [comment]
参考 https://github.com/esportsguy/react-videojs/blob/master/src/index.js，一般就是组织好插件需要的结构，然后在 `componentDidMount` 的时候取初始化第三方插件就行了。
