### ISSUE TITLE
Image组件无法显示

### ISSUE THREAD

**Issue by fyxruben** [amazeui/amazeui-react#123]
## 问题描述

omit把src属性过滤了。
```js
var restProps = omit(this.props, Object.keys(this.constructor.propTypes));
```
直接 `{... restProps}` 也就没有了`src`属性

> 不止`Image`，包括`Input`无法正常显示`checkbox`

**Comment by minwe** [comment]
谢谢反馈，可以先降级回 `v1.1.2`，我们会尽快修复这个问题。
