### ISSUE TITLE
官网使用chrome无法访问

### ISSUE THREAD

**Issue by Pines-Cheng** [amazeui/amazeui-react#125]
## 问题描述
官网使用chrome无法访问，safari也不行。

## 产生环境

- **设备及型号：** Mac
- **操作系统及版本：** OSX 10.11
- **浏览器及版本：** Chome51.0

### 操作方式
在浏览器直接输入url，如：`http://amazeui.org/react/components/modal`，按回车，就会报错。
报错如下：
```
app.4a78bba.min.js:1 Uncaught SyntaxError: Unexpected token <
```
而在首页通过超链接一层一层点进去就没问题。

**Comment by minwe** [comment]
JS 路径有点问题，已经修复。
