### ISSUE TITLE
build后需要做什么特殊配置吗

### ISSUE THREAD

**Issue by tihumihu** [amazeui/amazeui-react#126]
npm run build后amazeui.css和app.js
路径不对，引用不到。代码发布服务器，访问www下的index.html文件访问不到内容。求高手指点，发布包需要做什么配置吗？

**Comment by minwe** [comment]
你是说这个项目么？build `amazeui.css` 会换成 CDN 的路径，`app.js` 会重命名成 `app.be232d5.min.js` 类似这样的形式。

我们针对自己服务器的设置做了一些特殊的配置，如果你要放在自己的服务器上的话，把

https://github.com/amazeui/amazeui-react/blob/master/docs/app.js#L52 改为

```js
<Router history={hashHistory}>
```

再 build。
