### ISSUE TITLE
npm run examples 报错

### ISSUE THREAD

**Issue by fengnovo** [amazeui/amazeui-react#136]
npm install gulp -g && npm install
开发及文档
npm start
构建
npm run build
示例
npm run examples

# 之后报错！！！

ERROR in multi server-rendering
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tusm/Desktop/0702/0907/react/amazeui-react-master/examples/server-rendering/app.js in /Users/tusm/Desktop/0702/0907/react/amazeui-react-master
 @ multi server-rendering

**Comment by lwxyfer** [comment]
嗯，是报错了，我先检查下问题。 但不影响正常使用。

**Comment by xfworld** [comment]
同样的错误，启动后示例不能用呢

**Comment by zhoulijie** [comment]
同上

**Comment by minwe** [comment]
pull 一下最新的代码就能跑起来了。

**Comment by fengnovo** [comment]
可以运行示例了
