### ISSUE TITLE
一个js里创建多个组件的问题

### ISSUE THREAD

**Issue by SendLessLove** [amazeui/amazeui-react#146]
## 怎么解决 一个js里创建多个组件并且不报错呢

我就是想在一个js里创建多个React.Component,但是会遇到报错，怎么解决Declare only one React component per file 这个报错呢？

![no-multi-comp](https://cloud.githubusercontent.com/assets/15671748/21980574/cc7703c6-dc1e-11e6-9bb8-837aad13c54a.png)

**Comment by minwe** [comment]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-multi-comp.md

改 ESLint 配置

**Comment by minwe** [comment]
`.eslintrc` 里面加上 `"react/no-multi-comp":  "off"`

**Comment by SendLessLove** [comment]
谢谢你，问题解决了！
