### ISSUE TITLE
gulp task copy，复制fonts文件夹的文件时，有bug

### ISSUE THREAD

**Issue by jin0121** [amazeui/amazeui-react#19]
你好，我的系统是WIN8.1 64BIT
执行gulp dev时，执行任务copy的时候，发现node_modules/amazeui/dist/fonts/文件夹中的文件没有正确复制到制定路径，而是直接复制到dist/下，原因是indexOf中的参数，改成：
else if (file.path.indexOf('\\\\amazeui\\\\dist\\\\fonts\\\\') > -1)
就正常了，请问是系统的问题吗？

**Comment by Minwe** [comment]
windows 和 *nix 路径格式不一样，我看一下怎么处理。

**Comment by jin0121** [comment]
和jquery版的那样，copy fonts独立成一个任务也可以。
gulp.task('copy:fonts', function() {
  return gulp.src('node_modules/amazeui/dist/fonts/*')
    .pipe(gulp.dest('dist/fonts'));
});

**Comment by Minwe** [comment]
加了个路径转换，你重新 pull 试一下。

**Comment by jin0121** [comment]
不好意思，现在才发现issue发错地方，应该是发到react-starter-kit。
我试过了，文件还是被复制到dist文件夹下，而不是dist/fonts文件夹里

**Comment by Minwe** [comment]
这回应该没问题了。

**Comment by jin0121** [comment]
恩，没有问题啦，THX
