### ISSUE TITLE
使用 Webpack 时报错

### ISSUE THREAD

**Issue by geekdada** [amazeui/amazeui-react#21]
我用 `babel-loader` 转换 `jsx` 语法，浏览器报错如下：

```
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
main.js:57748 Warning: Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactory
main.js:53700 Uncaught TypeError: Cannot read property '__reactAutoBindMap' of null
```

**Comment by Minwe** [comment]
loader 配置有问题，JSX 没有转换。我们都是用 `.js` 做扩展名的，所以配置里 `.js` 的文件也要转换。

**Comment by geekdada** [comment]
我也是用 `.js` 做扩展名。以下是我的 loader 配置：

```js
{
      test: /\.(js|jsx)$/,
      exclude: /node_modules/,
      loader: 'react-hot!babel-loader'
}
```

**Comment by geekdada** [comment]
我知道为什么了，被 exclude 了。。。

**Comment by Minwe** [comment]
loader 顺序有问题？

**Comment by geekdada** [comment]
如果让 `babel` 处理所有来自 `node_modules` 的文件，每次消耗的时间会非常的长。这一点在 `babel-loader` 中也提到了: https://github.com/babel/babel-loader/tree/v5.1.3#babel-loader-is-slow

**Comment by Minwe** [comment]
NPM 上的版本已经转换过，里面应该没有了 JSX 了，按道理不用再转了啊。我在 https://github.com/amazeui/react-starter-kit 用没遇到过问题，没用过 Webpack，按理应该是一样。

**Comment by geekdada** [comment]
那就应该不是 JSX 未转换的问题

**Comment by geekdada** [comment]
没注意 `amazeui-react` 要求 0.13.3 以上版本的 React，更新以后不会有那个错误了。
