### ISSUE TITLE
amazeui-react不打算支持IE8吗？代码中有IE8不能使用的关键字default

### ISSUE THREAD

**Issue by jin0121** [amazeui/amazeui-react#22]
constants.js文件中的STYLES中包含了一个IE8不能使用的关键字default，amazeui-react不打算支持IE8？
另外想问问，amazeui-react什么时候出正式版啊？近期有更新的计划吗？

**Comment by xfworld** [comment]
IE核心微软都放弃重做了，还支持IE8...

**Comment by Minwe** [comment]
IE8 应该不太考虑了。beta 和正式版的区别不会太大，基本上就是一些动画细节之类的完善。
