### ISSUE TITLE
什么时候能添加表单验证

### ISSUE THREAD

**Issue by iyoukeyyewei** [amazeui/amazeui-react#23]

**Comment by Minwe** [comment]
还在考查表单验证在 React 中的实现方式，暂时无法确定什么时候会添加。

**Comment by xfworld** [comment]
@Minwe  表单验证会考虑什么组件来实现？有备选的不

**Comment by Minwe** [comment]
可以参考：

- https://github.com/christianalfoni/formsy-react/
- https://github.com/prometheusresearch/react-forms
