### ISSUE TITLE
关于怎么加入到amazeui-react的问题

### ISSUE THREAD

**Issue by msdlisper** [amazeui/amazeui-react#25]
我fork了后,想加入开发
按我的理解就是在src里面写源代码,在doc里面写测试和文档,问题是每次写了代码JS都被打包成commonjs的模块,集成在/dist/doc/app.js里面,想设个断点都没法啊,  你们是怎么单独来测试自己的那个模块?

**Comment by msdlisper** [comment]
我发现在gulpfile.js里把https://github.com/amazeui/amazeui-react/blob/master/gulpfile.js#L92 注释去掉就可以在前端断点测试了(debug:true),这是browserify的功劳

**Comment by Minwe** [comment]
我们一般是用 `console`，断点用得不多。
