### ISSUE TITLE
development roadmap or schedule ?

### ISSUE THREAD

**Issue by fuxiaohei** [amazeui/amazeui-react#29]
Is there a roadmap or release schedule ?

Now `amazeui-react` is in `1.0.0-beta1`.... 

**When** new and stable release ?

**Comment by Minwe** [comment]
React 目前只是作为 jQuery 版 https://github.com/allmobilize/amazeui 的衍生版本，目前还没有明确发展规划，可能要积累更多的 React 开发经验才会有相关的规划。

`beta1` 应该算是准正式版了，只是一些动画细节之类的完善，同时也希望收到更多用户的反馈，因此正式版发布时间还不太确定，应该会在未来 3 个月内。

**Comment by minwe** [comment]
See https://github.com/amazeui/amazeui-react/milestones
