### ISSUE TITLE
amazeui用webpack打包的时候会将react引入两次

### ISSUE THREAD

**Issue by alert888** [amazeui/amazeui-react#37]
amazeui用webpack打包的时候会将react引入两次，建议将amazeui的源码当中对react的依赖取消掉。

目前我的做法是 cd ./node_modules/amazeui-react/ && npm remove react,如果有更好的解决方式麻烦告诉我

**Comment by alert888** [comment]
或者将amazeui当中的react暴露出来。

**Comment by minwe** [comment]
你把 `./node_modules/amazeui-react/package.json`

改为：

https://github.com/amazeui/amazeui-react/blob/6e854f9496e7978cee2a7fb44f0f13d4428980c5/package.json

测试一下。
