### ISSUE TITLE
关于滚动检测的一个问题

### ISSUE THREAD

**Issue by wenshiqi0** [amazeui/amazeui-react#39]
我在使用UI做一个单页的应用，包括路由也是自己实现的非常简单的，只是一个dom的替换而已，但是有一个问题，因为我的每一个子页面展示就是一个react的component，所以实际上我就是在主component上面来替换展示的component，这里我在一个component上使用了滚动检测来添加动画，但是一但翻页到另外一个展示component的时候，就会因为虚拟dom的原因使得真实dom被删除替换下来了，这样就会报错
<pre>
<code>
Uncaught Error: Invariant Violation: Component (with keys: 
getDOMNode,getClassSet,setClassNamespace,prefixClass,checkIsInView,checkRAF,props,context,sta
te,refs,_reactInternalInstance,_scrollListener,_resizeListener,_orientationListener,_timer) 
contains `render` method but is not mounted in the DOM
</code>
</pre>
我认为是不是在滚动检测里面也应该加一个测试，一旦发现监听的dom不在了，就应该删除这个事件，虽然这个错误并不影响使用，但是会在开发者工具里面不停地抛出错误

**Comment by minwe** [comment]
谢谢反馈！

**Comment by minwe** [comment]
麻烦使用 https://github.com/minwe/amazeui-react/blob/e859bbb054b58bbeb1eb8793879b5df82cd8d16c/src/ScrollSpy.js 测试一下，看看问题还有没有。

**Comment by minwe** [comment]
麻烦使用 6cddea0 测试一下，看看问题还有没有。

https://github.com/amazeui/amazeui-react/blob/6cddea05e168c6c7522bb7c98dd91e77e0c9642f/src/ScrollSpy.js

**Comment by minwe** [comment]
暂时关闭，如有问题，再重开。
