### ISSUE TITLE
npm安装amazeui-react错误

### ISSUE THREAD

**Issue by vncnliu** [amazeui/amazeui-react#41]
PS D:\html\react\react-starter-kit-master> npm install amazeui-react
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "amazeui-react"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: amazeui-react@'*'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0-alpha3","1.0.0-beta1"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'react-starter-kit'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     D:\html\react\react-starter-kit-master\npm-debug.log
PS D:\html\react\react-starter-kit-master>

**Comment by minwe** [comment]
把 `D:\html\react\react-starter-kit-master\package.json` 里面搜索 `"amazeui-react"`，后面的值改为 `"latest"`.
