### ISSUE TITLE
无法使用自定义按钮，关闭modal

### ISSUE THREAD

**Issue by Pliman** [amazeui/amazeui-react#42]
某些情况下，confirm的时候，不想关闭dialog，比如dialog中有内容，但是确定的时候，内容验证失败，需要重新填写，这个时候，不想关闭modal。本来想用onConfirm，return false；来禁止关闭modal结果不行，看了实现代码，从机制上没有提供次功能。

ModalTrigger.js L93
onConfirm: createChainedFunction(this.close, this.props.onConfirm)
表示点击确定的时候，先执行close，再执行this.props.onConfirm，无论onConfirm执行的执行的结果如何，close都会执行。(createChainedFunction.js L36)

不能阻止modal关闭，少了此功能。
一种可能的修改方式是：

ModalTrigger.js L93
onConfirm: createChainedFunction(this.props.onConfirm, this.close)

createChainedFunction.js L36
one.apply(this, arguments) === false || two.apply(this, arguments);
去掉L37

onCancel同理。

**Comment by Pliman** [comment]
可以用自定义按钮，ref modal，实现这个功能，不过太绕弯路了。

对amazeui不是很熟悉，请问还有其他比较简单的方法没有？

**Comment by xfworld** [comment]
你可以自己定义按钮去实现modal事件的操控的，不要使用onConfirm这样的原生事件；

在modal上增加几个控制按钮，比如新增，修改，关闭，你可自行实现按钮绑定的事件；

**Comment by Pliman** [comment]
现在是这样做的，但是感觉还是不太便。

还是希望onConfirm，可以有能力阻止close，就像一般的form submit，如果onsubmit="return false;"，表单就不提交。
