### ISSUE TITLE
升级至 React 0.14.0 及 react-router 1.0.0

### ISSUE THREAD

**Issue by minwe** [amazeui/amazeui-react#45]

**Comment by Pyiner** [comment]
这个升级大概什么时候可以完成？

**Comment by minwe** [comment]
预计月底。

**Comment by kazaff** [comment]
关注，希望早日更新

**Comment by ccdevote** [comment]
在哪里可以看到React 0.14.0的开发进度和提交记录？

**Comment by minwe** [comment]
@ccdevote 目前没有，现在其实是可以和 0.14.0 一起用的，0.14.0 的代码还保留了旧的 API，只是会有一些提示的 log。

**Comment by minwe** [comment]
组件已经升级到 React v0.14.x，需要的用户可以从 npm 下载 v1.0.0-beta2。

感谢 @sunnylqm！
