### ISSUE TITLE
方法命名误导

### ISSUE THREAD

**Issue by rlog** [amazeui/amazeui-react#48]
我在用Dropdown组建的时候想调用 `setDropdownState()` 来主动关闭下拉层。  发现它需要传 true/false , 而不是 {show: true/false} 。 这样做确实能让开发者稍微方便点，但react里如果有 set...State 字样出现，直觉就是传一个object，而不是一个布尔值。 希望能修改下

**Comment by minwe** [comment]
我改个名好了，改参数类型略繁琐。
