### ISSUE TITLE
Dropdown组件的componentWillMount()方法应修改为componentWillUnmount()方法

### ISSUE THREAD

**Issue by khejing** [amazeui/amazeui-react#49]
把amazeui-react和React Router一起用的情况下，如果一个Dropdown Item的点击实现是视图跳转，那么这里就会有问题。视图跳转会导致Dropdown组件被卸载，而这里的EventHandler没有被删除，于是就会执行handleOuterClick，而里面的React.findDOMNode(this)会导致React报：

```js
Uncaught Error: Invariant Violation:
Component (with keys: getDOMNode,getClassSet,setClassNamespace,prefixClass,setDropdownState,handleKeyup,
handleOuterClick,bindOuterHandlers,unbindOuterHandlers,handleDropdownClick,props,context,
state,refs,_reactInternalInstance) contains `render` method but is not mounted in the DOM
```

**Comment by khejing** [comment]
能否回应下？如果觉得不是问题，或者是我理解错了，我就给关了

**Comment by minwe** [comment]
前段时间没顾上这边，最近细看处理一下，谢谢。

**Comment by minwe** [comment]
看了一下代码，这个问题在 a299e4b0fbdd9a86ac2a9d69706f5eb6064bdbd5 中已经处理了。

你更新到 beta2 试一下，问题应该不存在了。

谢谢！

**Comment by khejing** [comment]
好的，我更新下




-------- 原始邮件 --------
发件人：Minwe LUO <notifications@github.com>
时间：周二 12月8日 15:24
收件人：amazeui/amazeui-react <amazeui-react@noreply.github.com>
抄送：Will Lee <khejing@hotmail.com>
主题：Re: [amazeui-react] Dropdown组件的componentWillMount()方法应修改为componentWillUnmount()方法 (#49)

**Comment by minwe** [comment]
先关闭了，还有再打开。
