### ISSUE TITLE
npm初始化 amazeui-react项目，dev可以生成，但是build失败

### ISSUE THREAD

**Issue by ExpressGit** [amazeui/amazeui-react#55]
gulp build
amazeui-react-master\src\mixins\DimmerMixin.js: Unexpected token (40:6) while parsing file: amazeui-react-master\src\mixins\DimmerMixin.js
请问这是什么原因？

**Comment by minwe** [comment]
https://github.com/amazeui/amazeui-react/blob/master/src/mixins/DimmerMixin.js#L40

根据源码来看，没有转换 JSX。

**Comment by minwe** [comment]
没有后续反馈，视为已经解决。如需要帮助请重开。
