### ISSUE TITLE
DateTimeInput 组件弹出位置问题

### ISSUE THREAD

**Issue by crquans** [amazeui/amazeui-react#57]
DateTimeInput 组件在表格中时，点击弹出框位置计算错误，会在表格左上角弹出

**Comment by minwe** [comment]
具体结构是什么样的？

**Comment by minwe** [comment]
http://stackoverflow.com/questions/1044988/getting-offsettop-of-element-in-a-table

**Comment by arcsecw** [comment]
在Tabs里用DateTimeInput组件的时候位置错误
`<Tab>
<Tabs.Item eventKey="1" title="xxx" >
<DateTimeInput/>
<Tabs.Item/>
</Tab>`
调试发现是此次修改导致的位置计算错误
用之前的offset top 是正确的

**Comment by arcsecw** [comment]
@minwe 推测原来的方法之所以在表格中位置错误是因为`ReactDOM.findDOMNode(this.refs.dateInput);`参数没有传递合适的elem
