### ISSUE TITLE
Input组件的value绑定了数据之后无法输入

### ISSUE THREAD

**Issue by vimac** [amazeui/amazeui-react#59]
举个例子：
```
<Input type="text" name="brand" label="品牌" placeholder="品牌名称" value={this.state.brand} />
```

google后发现了这个：

http://stackoverflow.com/questions/28315205/why-does-react-make-inputtype-text-fields-readonly-unless-i-supply-onchange

然后改成:
```
<Input type="text" name="brand" label="品牌" placeholder="品牌名称" value={this.state.brand} onChange={function(){}}/>
```

仍然无效

**Comment by minwe** [comment]
http://facebook.github.io/react/docs/forms.html

默认值使用 `defaultValue`

**Comment by vimac** [comment]
我尝试了defaultValue
<Input type="text" name="brand" label="品牌" placeholder="品牌名称" defaultValue={this.state.brand} />

编辑是没问题了，然而默认值也不出现了，直接就空白

**Comment by vimac** [comment]
解决了，是我没有理解Controlled Component和Uncontrolled Component的差异和作用

**Comment by minwe** [comment]
有什么好的帮助理解的文章可以贴上来，供以后相同疑惑的同学参考。

**Comment by vimac** [comment]
我就还是仔细阅读了几遍你给的链接

**Comment by lvybriage** [comment]
我也遇到了相同的问题，设置默认值之后，可以修改，但是默认值不显示了

**Comment by allinshang** [comment]
<Input
  onChange={this.handleChange}
  value={inputValues}
 />
handleChange = (e) => {
        this.setState({
            inputValues: e.target.value
        })
    }

希望有帮忙。我这么做解决了这个问题

**Comment by allinshang** [comment]
`<Input
                    onChange={this.handleChange}
                    value={inputValues}
                />`
`handleChange = (e) => {
        this.setState({
            inputValues: e.target.value
        })
    }`
希望有帮忙。我这么做解决了这个问题

**Comment by coding2world** [comment]
<input type="text"  value={this.state.button} onChange={() =>this.inputValChanged()} ref="txt"/>
加上ref="txt"就行了
