### ISSUE TITLE
Bug: Selected组件，默认的onChange事件报错：this.state.value.split is not a function

### ISSUE THREAD

**Issue by openwings** [amazeui/amazeui-react#64]
**问题描述**

版本 1.0.0-beta2
68行，
当this.state.value = 2的时候，这个三元表达式会成立，于是调用了非[]数组的split方法，因此报错

**产生环境**

- 操作系统及版本：
Mac OS 10.x
- 浏览器及版本：
Chrome
- 演示地址：
无
**复现步奏**

1. Selected组件使用
2. 配置props和data（不要multiple，是单选）
3. 点击出现下拉后，选择，查看console，报错信息

**Comment by openwings** [comment]
补充：
```
data = [{
  value: 'all',
  label: '全部'
},{
  value: 1,
  label: '国家1'
}]
```

**Comment by openwings** [comment]
*没人维护了么？*

__答案：value字段不能使用，数字，必须要string :-1: __

**Comment by minwe** [comment]
忙于其他事务暂未顾上这边，见谅。

我把这个细节添加到文档中。谢谢！
