### ISSUE TITLE
滚动检测ScrollSpyNav插件服务器端渲染的问题

### ISSUE THREAD

**Issue by Traceray** [amazeui/amazeui-react#68]
我在使用ScrollSpyNav插件开发SPA应用时，开启服务器端渲染的时候会报 window is not definded，我知道这不是插件本身的问题，但是想知道有什么办法可以解决这个问题么？

**Comment by Traceray** [comment]
我暂时将“./utils/Events.js”中的源码做了修改：将全局变量bind ,unbind ,prefix 修改为局部变量。望修正。

**Comment by minwe** [comment]
目前的版本还没有考虑后端渲染，后续会逐步完善。

**Comment by magicae** [comment]
同样有这个问题
需要patch utils/Events
