### ISSUE TITLE
怎样默认显示 Modal 对话框 

### ISSUE THREAD

**Issue by programnext** [amazeui/amazeui-react#83]
目前打开一个对话框需要用于点击button。 能不能根据一个isModalActive的prop去默认显示对话框啊？

**Comment by minwe** [comment]
暂时没有提供默认显示的选项，modal 现在的模式设计得不太好，回头看看能不能加个选项吧。

**Comment by programnext** [comment]
我之前用的是react-bootstrap， 后来发现amazeui-react的功能更加强大。 React-bootstrap的 Modal在以前的版本中也需要使用一个类似ModalTrigger的组件， 从React 0.14 之后，就简化为只需要Modal就可以了， 而且引入了一个show参数： https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L148

**Comment by zhang-z** [comment]
我提交了pull request #108 , 参照[react-bootstrap](https://react-bootstrap.github.io/components.html#modals-live)，用`show`和`onHide`来打开Modal：

    <ModalTrigger modal={modal} show={this.state.showModal} onHide={this.close}/>

具体的用例更新在文档里
