### ISSUE TITLE
 npm install amazeui-react --save-dev失败

### ISSUE THREAD

**Issue by LiangKevin** [amazeui/amazeui-react#88]
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "amazeui-react" "--save-dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: amazeui-react@'*'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0-beta2","1.0.0-beta1","1.0.0-alpha3"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'node-express-init'
npm ERR! notarget

**Comment by minwe** [comment]
这不应该出问题啊，你 `package.json` 里面设版本号了？

建议你升级到 Node 4.x 最新版。

**Comment by LiangKevin** [comment]
知道怎么回事了，必需指定版本号才行。。。。
