### ISSUE TITLE
把amazeui-react包含到系统中，webpack打包时报错

### ISSUE THREAD

**Issue by hodgevk** [amazeui/amazeui-react#89]
ERROR in ./~/amazeui-react/~/object.omit/index.js
Module not found: Error: Cannot resolve module 'isobject' in 
/****/node_modules/amazeui-react/node_modules/object.omit
 @ ./~/amazeui-react/~/object.omit/index.js 10:15-34

ERROR in ./~/amazeui-react/~/object.omit/index.js
Module not found: Error: Cannot resolve module 'for-own' in 
/****/node_modules/amazeui-react/node_modules/object.omit
 @ ./~/amazeui-react/~/object.omit/index.js 11:13-31

**Comment by minwe** [comment]
如果 npm 版本是 3.x，换成 2.x。
