### ISSUE TITLE
打包问题&&请求问题

### ISSUE THREAD

**Issue by xfworld** [amazeui/amazeui-react#92]
@minwe 
这个版本的打包貌似和touch版本不太一样，gulp 和 webpack的差异
这个版本是不是不能单独的打包成一个js，

另外我想问下，react里面对于数据的请求是不是都是用的这个方式：
<pre>
<code>
function checkStatus(response) {
      if (response.status >= 200 && response.status < 300) {
        return response;
      } else {
        var error = new Error(response.statusText);
        error.response = response;
        throw error;
      }
    }

    fetch('https://api.github.com/orgs/amazeui/events')
      .then(checkStatus)
      .then(res => {
        return res.json();
      })
      .then(data => {
        this.updateDataSource(data);
      })
      .catch(error => {
        console.log('Request failed: ', error)
      });
</code>
</pre>

**Comment by minwe** [comment]
- 可以打包。例子里没有写打包的配置而已。
- Fetch 是浏览器的新 API，可以继续使用 Ajax：http://www.w3ctech.com/topic/854

**Comment by xfworld** [comment]
好的，收到；
学习ing
