### ISSUE TITLE
TopBar控件在小窗口尺寸界面时出现的问题

### ISSUE THREAD

**Issue by flyzb618** [amazeui/amazeui-react#96]
当窗体变小时，自动出现缩略图标，这时react版存在3个问题，而jquery版却都不存在这些问题：
1 ： 既然出现缩略图标，那么按钮应该自动隐藏；
2：  点击按钮后，所有按钮不自动隐藏；
3： 点击缩略图标，所有按钮切换自动隐藏模式。

**Comment by atom2ueki** [comment]
你说的缩略图标是汉堡图标么，应该是responsive的css问题，2，3点没看明白，如果有gif截图会比较清楚了解问题，可以用这个工具 https://github.com/lepht/licecap

**Comment by flyzb618** [comment]
![topbar](https://cloud.githubusercontent.com/assets/7271358/13174055/30bc8a42-d73c-11e5-825b-d42e99b03451.gif)
我的版本设置"amazeui": "^2.5.2", "amazeui-react": "latest",
如附件所示，
1、当我缩小窗口尺寸时，出现缩略图标，“用车申请”和“页面2”从上方移到下方，而正确的方式应该隐藏；
2、点击“用车申请”按钮后，“用车申请”和“页面2”都应该自动隐藏。

**Comment by flyzb618** [comment]
![topbar_amaze_react](https://cloud.githubusercontent.com/assets/7271358/13174343/011f7bb2-d73e-11e5-9a1c-3e7ebf1ba3b5.gif)
这是amaze react 站点上topbar控件的效果，
没有上述按照amaze react start kit开发出现的问题，当窗口缩小时，出现缩略图标时，按钮正确隐藏。
但也存在着问题，就是点击“开始使用”后，整个按钮仍让没有自动隐藏。

**Comment by flyzb618** [comment]
![topbar_amaze_juqery](https://cloud.githubusercontent.com/assets/7271358/13174516/0f66113a-d73f-11e5-9cc0-9541cc80b334.gif)
这是amaze jquery站点上topbar控件的效果,所有行为都是正确的。

**Comment by minwe** [comment]
@flyzb618 我现在的处理方式手动绑一个事件，点击链接的时候关闭下拉菜单。你可以参考 https://github.com/amazeui/amazeui-react/blob/3378e27eab2c67a67847b45d9056eff4694166a2/examples/admin/components/Header.js#L16-L20 一下。

React 中处理这种问题不是很方便，后面如果发现在更好的处理方式再改进吧。
