### ISSUE TITLE
作为开发者，谈下我对妹子UI的一些看法

### ISSUE THREAD

**Issue by catxuxiang** [amazeui/amazeui-react#98]
公司让我定一个移动WEB框架，本来选定了WEX5，因为里面的DEMO比较完善，好多DEMO改改就大概能用了，但经过一段时间的研究，感觉WEX5的学习曲线比较陡，而且不利于团队分工，于是决定换框架。

然后看了些国外的开源框架，感觉国外的设计风格和中国人喜好的风格还是有些区别的，于是，就主要关注国内的框架，便注意到了妹子UI。

妹子UI分为三系：源生系列、React系列、Touch系列。这三系我都大概了解了一下。从反馈上来看，源生系列应该是大家使用比较多的，但我个人是React.js的坚定支持者，喜欢React.js的精简设计理念。从妹子UI的发展来看，妹子UI的主要开发者在这一点上应该与我的想法是一致的，所以，妹子UI才会出React系列及Touch系列（Touch系列同样采用了React.js）。如果说起React系列与Touch系列的最大区别，我想应该是Touch系列采用了Flexbox布局方式吧。

但对于妹子UI这三系的选择让我犯了难。我认为，对于移动用户来说，首先要解决的问题就是兼容者问题，不可能让用户为了用你的功能而换部手机。从兼容性的测试结果来看，源生系>React系>Touch系。Touch系排在最后的最大原因应该就是采用Flexbox布局，DEMO在小米3及IPHONE4S上均有兼容性问题。而源生系相对来说是比较重的，也不符合精简设计理念，所以，让我放弃React.js而采用源生系，是一个让人难受的决定。而React系呢，感觉是两者的中间品，兼容性比Touch系好点（DEMO在IPHONE4S上运行有点小BUG），也采用了React.js技术。但Touch系框架的完整度感觉是三系中最低的。

无论是人还是公司，精力都是极为有限的，希望妹子UI团队能在仔细权衡后选择一个系重点开发，否则，贪大不精最后是难以做成一件伟大的产品的。我个人希望将React系作为重点开发的对象。

以上是我个人的一点小建议，希望妹子UI团队采纳，谢谢！

**Comment by atom2ueki** [comment]
其实已经开源的项目就该多靠我们自己来开发了，比如我和你都钟爱react，看到bug或者有新的东西就做一份贡献来得更实在

**Comment by catxuxiang** [comment]
楼偏了。我的意思是现在有三个分支需要完善，而且三个分支要解决的其实是一件事吧。我们应该先确定好一个分支，把大家的力量都集中起来把这个分支做好。

**Comment by minwe** [comment]
jQuery 版起步较早，加上 jQuery 的相关开发模式也很成熟，所以相对完善一些。

React 刚兴起，有些场景使用很方便，但有些场景就不那么顺手，这应该是大家在使用过程中都会遇到的。

Flexbox 对于国内乱七八糟的安卓环境，只能用于一些浏览器内核相对确定的环境中。

**Comment by catxuxiang** [comment]
感谢大大的回复，看来Flexbox在国内的推广应该不会太顺利，个人希望React能走得更好，谢谢大大。

**Comment by Pines-Cheng** [comment]
bootstrap4也加入了Flexbox，但是默认是关闭的，需要自己手动开启。无论如何，这个趋势是好的。
